### PR TITLE
Faster sharing of password

### LINKED ISSUE #695: [BUG]: Password shares when sharing to large number of users take a long time to show up
### ⚠️ This issue respects the following points: ⚠️

- [X] This is a _single_ **bug**, not a question or a configuration/webserver/proxy issue.
- [X] This is not a bug in the [browser extension](https://github.com/marius-wieschollek/passwords-webextension) or another client.
- [X] This issue is **not** already reported on Github _(I've searched it)_.
- [ ] Nextcloud Server and the Passwords App **is** up to date. See [Nextcloud Apps](https://apps.nextcloud.com/apps/passwords).
- [X] There are no warnings and errors reported in the Passwords App settings in the admin area
- [X] The following apps are not installed: Rainloop

### Server Information

```shell
{
    "version": {
        "server": "28.0.9.6",
        "app": "2023.12.32",
        "lsr": false,
        "php": "8.2.23",
        "cronPhp": "8.2.23"
    },
    "environment": {
        "os": "Linux",
        "architecture": "x86_64",
        "bits": 64,
        "database": "mysql",
        "cron": "cron",
        "proxy": false,
        "sslProxy": true,
        "subdirectory": false
    },
    "services": {
        "images": "imagick",
        "favicons": "default",
        "previews": "default",
        "security": "hibp",
        "words": "auto",
        "previewApi": false,
        "faviconApi": false
    },
    "status": {
        "autoBackupRestored": false
    },
    "settings": {
        "channel": "stable",
        "nightlies": false,
        "handbook": false,
        "performance": 5
    },
    "encryption": {
        "sse": {
            "SSEv1r1": false,
            "SSEv1r2": true,
            "SSEv2r1": false,
            "SSEv3r1": false,
            "none": false,
            "default": "SSEv1r2"
        },
        "cse": {
            "CSEv1r1": false,
            "none": true,
            "default": "none"
        }
    }
}
```

### Client Information

Browser and Version:
Client OS and Version:

### Bug description

- When I share passwords to many users (1000+), it is taking a long time for the share to show up in the passwords app of the sharee
- Sometimes 45 minutes, sometimes 3 hours and so on
- My specific use case is generating random passwords and sharing via the API to 1000+ users from a single user
- Sometimes when I force execute the `OCA\Passwords\Cron\SynchronizeShares` job using `occ` command, the passwords are seen instantly

### Steps to reproduce

1. Open the app
2. Add a new password 
3. Share to a user on your cloud
4. Repeat 1000 times
5. The sharee doesn't see the shared password instantly

OR

1. Use a script to generate random password 
2. Use the passwords API to share the generated passwords to a list of 1000+ users
3. The sharee doesn't see the shared password instantly

### Expected behavior

1. The sharee sees the shared password immediately

### Nextcloud Logs

_No response_

### Browser Logs

_No response_

### PR DESCRIPTION
**Pull request by akhil1508**
- Resolves https://github.com/marius-wieschollek/passwords/issues/695

### Technical details
- The method `removeSharedAttributes` runs for at least 10 minutes (sometimes more) without this fix on a system with about 10000 shared passwords
  - Most of the time, it isn't changing anything
  - It is the slowest method of all the ones run in `SynchronizeSharesJob` (sometimes `createNewShares` can be slow if a lot of passwords are created with `curl` but the cron route is not called - this is not a problem if passwords UI is the main consumer of the API)
- After the fix here to fetch passwords to remove shared attributes with a single indexed query, the method takes barely a second to run

### CODE REVIEW

File: src/lib/Migration/Version20250930.php [hunk 1]
```diff
@@ -0,0 +1,61 @@
...
+use OCP\DB\ISchemaWrapper;
+use OCP\Migration\IOutput;
+use OCP\Migration\SimpleMigrationStep;
+
+/**
+ * Class Version20250930
+ *
+ * @package OCA\Passwords\Migration
+ */
+class Version20250930 extends SimpleMigrationStep {
```
Comment (akhil1508) [inline src/lib/Migration/Version20250930.php:17]: @marius-wieschollek I'm not fully sure if this is the correct versioning :)

Comment (marius-wieschollek) [reply src/lib/Migration/Version20250930.php:17]: Looks good to me

**Review by marius-wieschollek — APPROVED** [review]
